### ISSUE TITLE
Drop rustc-serialize dependency

### ISSUE THREAD

**Issue by dtolnay** [starlab-io/xenstore-rs#3]
It has been deprecated: [announcement](https://users.rust-lang.org/t/deprecation-of-rustc-serialize/10485?u=dtolnay).

Is there any functionality you would require from another library before this would be possible?

**Comment by cardoe** [comment]
We actually migrated away and hadn't removed it from Cargo.toml. Thanks for reminding us. Merged the removal in 63e5a1d0bd880a1f9942c6b4aff1737efd168099.
